# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 646)
        MainWindow.setAcceptDrops(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_height = QtWidgets.QRadioButton(self.groupBox)
        self.radio_height.setObjectName("radio_height")
        self.gridLayout.addWidget(self.radio_height, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radio_both = QtWidgets.QRadioButton(self.groupBox)
        self.radio_both.setChecked(False)
        self.radio_both.setObjectName("radio_both")
        self.gridLayout.addWidget(self.radio_both, 0, 2, 1, 1)
        self.radio_noscale = QtWidgets.QRadioButton(self.groupBox)
        self.radio_noscale.setChecked(True)
        self.radio_noscale.setObjectName("radio_noscale")
        self.gridLayout.addWidget(self.radio_noscale, 0, 1, 1, 1)
        self.radio_width = QtWidgets.QRadioButton(self.groupBox)
        self.radio_width.setChecked(False)
        self.radio_width.setObjectName("radio_width")
        self.gridLayout.addWidget(self.radio_width, 0, 3, 1, 1)
        self.spin_height = QtWidgets.QSpinBox(self.groupBox)
        self.spin_height.setEnabled(False)
        self.spin_height.setMaximum(5000)
        self.spin_height.setProperty("value", 600)
        self.spin_height.setObjectName("spin_height")
        self.gridLayout.addWidget(self.spin_height, 3, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spin_width = QtWidgets.QSpinBox(self.groupBox)
        self.spin_width.setEnabled(False)
        self.spin_width.setMaximum(5000)
        self.spin_width.setProperty("value", 800)
        self.spin_width.setObjectName("spin_width")
        self.gridLayout.addWidget(self.spin_width, 2, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 5)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.button_del = QtWidgets.QPushButton(self.centralWidget)
        self.button_del.setObjectName("button_del")
        self.horizontalLayout_2.addWidget(self.button_del)
        self.button_browse = QtWidgets.QPushButton(self.centralWidget)
        self.button_browse.setObjectName("button_browse")
        self.horizontalLayout_2.addWidget(self.button_browse)
        self.button_upload = QtWidgets.QPushButton(self.centralWidget)
        self.button_upload.setObjectName("button_upload")
        self.horizontalLayout_2.addWidget(self.button_upload)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 2, 0, 1, 1)
        self.line_prefix = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_prefix.setText("")
        self.line_prefix.setObjectName("line_prefix")
        self.gridLayout_8.addWidget(self.line_prefix, 0, 1, 1, 2)
        self.spin_start_num = QtWidgets.QSpinBox(self.groupBox_4)
        self.spin_start_num.setMaximum(10000)
        self.spin_start_num.setProperty("value", 1)
        self.spin_start_num.setObjectName("spin_start_num")
        self.gridLayout_8.addWidget(self.spin_start_num, 2, 1, 1, 1)
        self.line_suffix = QtWidgets.QLineEdit(self.groupBox_4)
        self.line_suffix.setObjectName("line_suffix")
        self.gridLayout_8.addWidget(self.line_suffix, 1, 1, 1, 2)
        self.check_autostart = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_autostart.setObjectName("check_autostart")
        self.gridLayout_8.addWidget(self.check_autostart, 3, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 2, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 2, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.line_user = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_user.setText("")
        self.line_user.setObjectName("line_user")
        self.gridLayout_4.addWidget(self.line_user, 2, 1, 1, 2)
        self.line_host = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_host.setText("")
        self.line_host.setObjectName("line_host")
        self.gridLayout_4.addWidget(self.line_host, 0, 1, 1, 2)
        self.line_dir = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_dir.setText("")
        self.line_dir.setObjectName("line_dir")
        self.gridLayout_4.addWidget(self.line_dir, 4, 1, 1, 2)
        self.line_pass = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_pass.setText("")
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.gridLayout_4.addWidget(self.line_pass, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.spin_port = QtWidgets.QSpinBox(self.groupBox_2)
        self.spin_port.setMaximum(65536)
        self.spin_port.setProperty("value", 21)
        self.spin_port.setObjectName("spin_port")
        self.gridLayout_4.addWidget(self.spin_port, 1, 1, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 2, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 0, 3, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 684, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionUpdate_Settings = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Settings.setObjectName("actionUpdate_Settings")
        self.actionSend_Settings_To_Host = QtWidgets.QAction(MainWindow)
        self.actionSend_Settings_To_Host.setObjectName("actionSend_Settings_To_Host")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.action_ber = QtWidgets.QAction(MainWindow)
        self.action_ber.setObjectName("action_ber")
        self.menuFile.addAction(self.actionBeenden)
        self.menuOptions.addAction(self.actionUpdate_Settings)
        self.menuOptions.addAction(self.actionSend_Settings_To_Host)
        self.menu.addAction(self.action_ber)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radio_noscale, self.radio_both)
        MainWindow.setTabOrder(self.radio_both, self.radio_width)
        MainWindow.setTabOrder(self.radio_width, self.radio_height)
        MainWindow.setTabOrder(self.radio_height, self.spin_width)
        MainWindow.setTabOrder(self.spin_width, self.spin_height)
        MainWindow.setTabOrder(self.spin_height, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.line_host)
        MainWindow.setTabOrder(self.line_host, self.spin_port)
        MainWindow.setTabOrder(self.spin_port, self.line_user)
        MainWindow.setTabOrder(self.line_user, self.line_pass)
        MainWindow.setTabOrder(self.line_pass, self.line_dir)
        MainWindow.setTabOrder(self.line_dir, self.line_prefix)
        MainWindow.setTabOrder(self.line_prefix, self.line_suffix)
        MainWindow.setTabOrder(self.line_suffix, self.spin_start_num)
        MainWindow.setTabOrder(self.spin_start_num, self.check_autostart)
        MainWindow.setTabOrder(self.check_autostart, self.button_del)
        MainWindow.setTabOrder(self.button_del, self.button_upload)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoResize"))
        self.groupBox.setTitle(_translate("MainWindow", "Image Options"))
        self.radio_height.setText(_translate("MainWindow", "Height"))
        self.label.setText(_translate("MainWindow", "Scale to"))
        self.radio_both.setText(_translate("MainWindow", "Bo&th"))
        self.radio_noscale.setText(_translate("MainWindow", "Don\'t s&cale"))
        self.radio_width.setText(_translate("MainWindow", "Width"))
        self.label_3.setText(_translate("MainWindow", "Width"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.button_del.setText(_translate("MainWindow", "Delete Selection"))
        self.button_browse.setText(_translate("MainWindow", "Browse"))
        self.button_upload.setText(_translate("MainWindow", "Upload"))
        self.groupBox_4.setTitle(_translate("MainWindow", "File Options"))
        self.label_11.setText(_translate("MainWindow", "File Suffix"))
        self.label_10.setText(_translate("MainWindow", "File Prefix"))
        self.label_12.setText(_translate("MainWindow", "Start With"))
        self.line_suffix.setText(_translate("MainWindow", ".jpg"))
        self.check_autostart.setText(_translate("MainWindow", "Autostart"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FTP Options"))
        self.label_5.setText(_translate("MainWindow", "FTP Host"))
        self.label_7.setText(_translate("MainWindow", "Directory"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "User"))
        self.label_8.setText(_translate("MainWindow", "Port"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuOptions.setTitle(_translate("MainWindow", "Op&tions"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.actionUpdate_Settings.setText(_translate("MainWindow", "&Update Settings"))
        self.actionUpdate_Settings.setShortcut(_translate("MainWindow", "F5"))
        self.actionSend_Settings_To_Host.setText(_translate("MainWindow", "Upload &Settings"))
        self.actionSend_Settings_To_Host.setShortcut(_translate("MainWindow", "F6"))
        self.actionBeenden.setText(_translate("MainWindow", "Exit"))
        self.action_ber.setText(_translate("MainWindow", "About"))
